#PERSONAL INFORMATION

name=input("Type your Name: ")
nationality=input("Type your Nationality: ")
bday=input("Type your Date of Birth: ")
birthplace=input("Type your Place of Birth: ")
sex=input("Type your Sex: ")
maritalstatus=input("Type your Marital Status: ")
religion=input("Type your Religion: ")
address=input("Type your Address: ")
mobilenum=input("Type your Mobile Number: ")
email=input("Type your Email Address: ")

print("\n\t\t\tResume")
print("Personal Information")
print("Name:\t\t",name)
print("Nationality:\t\t",nationality)
print("Date of Birth:\t\t",bday)
print("Place of Birth:\t\t",birthplace)
print("Sex:\t\t",sex)
print("Marital Status:\t\t",maritalstatus)
print("Religion:\t\t",religion)
print("Address:\t\t",address)
print("Mobile Number:\t\t",mobilenum)
print("Email Address:\t\t",email)
